name: simple_store
description: Flutter package for ultra-simple local storage of any type using key-value format — zero boilerplate.
version: 1.0.0
repository: https://github.com/mohamedzebib22/simple_storage
homepage: https://github.com/mohamedzebib22/simple_storage


environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  # path: ^1.8.0



dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
